annotations:
  category: DeveloperTools
  images: |
    - name: consul
      image: docker.io/bitnami/consul:1.18.1-debian-12-r13
    - name: consul-exporter
      image: docker.io/bitnami/consul-exporter:0.12.0-debian-12-r4
    - name: os-shell
      image: docker.io/bitnami/os-shell:12-debian-12-r21
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.18.1
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: HashiCorp Consul is a tool for discovering and configuring services in
  your infrastructure.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/consul/img/consul-stack-220x234.png
keywords:
- discovering
- configuring
- services
maintainers:
- name: Broadcom, Inc. All Rights Reserved.
  url: https://github.com/bitnami/charts
name: consul
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/consul
version: 11.1.7
